version: '3.8'

services:
  server:
    build: .
    command: npm start
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass contraseñaderedis.123456